# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created: Fri Aug  1 16:21:28 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Interface(object):
    def setupUi(self, Interface):
        Interface.setObjectName(_fromUtf8("Interface"))
        Interface.setWindowModality(QtCore.Qt.ApplicationModal)
        Interface.resize(500, 778)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Interface.sizePolicy().hasHeightForWidth())
        Interface.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(Interface)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frameSyncExec = QtGui.QFrame(Interface)
        self.frameSyncExec.setEnabled(True)
        self.frameSyncExec.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameSyncExec.setFrameShadow(QtGui.QFrame.Raised)
        self.frameSyncExec.setObjectName(_fromUtf8("frameSyncExec"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frameSyncExec)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btSyncStop = QtGui.QPushButton(self.frameSyncExec)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btSyncStop.sizePolicy().hasHeightForWidth())
        self.btSyncStop.setSizePolicy(sizePolicy)
        self.btSyncStop.setObjectName(_fromUtf8("btSyncStop"))
        self.gridLayout_4.addWidget(self.btSyncStop, 4, 2, 1, 1)
        self.lblSyncExec = QtGui.QLabel(self.frameSyncExec)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSyncExec.setFont(font)
        self.lblSyncExec.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSyncExec.setObjectName(_fromUtf8("lblSyncExec"))
        self.gridLayout_4.addWidget(self.lblSyncExec, 1, 0, 1, 4)
        self.btSyncStep = QtGui.QPushButton(self.frameSyncExec)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btSyncStep.sizePolicy().hasHeightForWidth())
        self.btSyncStep.setSizePolicy(sizePolicy)
        self.btSyncStep.setObjectName(_fromUtf8("btSyncStep"))
        self.gridLayout_4.addWidget(self.btSyncStep, 4, 3, 1, 1)
        self.btSyncStart = QtGui.QPushButton(self.frameSyncExec)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btSyncStart.sizePolicy().hasHeightForWidth())
        self.btSyncStart.setSizePolicy(sizePolicy)
        self.btSyncStart.setMinimumSize(QtCore.QSize(0, 0))
        self.btSyncStart.setObjectName(_fromUtf8("btSyncStart"))
        self.gridLayout_4.addWidget(self.btSyncStart, 4, 0, 1, 1)
        self.btSyncPause = QtGui.QPushButton(self.frameSyncExec)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btSyncPause.setFont(font)
        self.btSyncPause.setObjectName(_fromUtf8("btSyncPause"))
        self.gridLayout_4.addWidget(self.btSyncPause, 4, 1, 1, 1)
        self.txtSyncStatus = QtGui.QLineEdit(self.frameSyncExec)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSyncStatus.sizePolicy().hasHeightForWidth())
        self.txtSyncStatus.setSizePolicy(sizePolicy)
        self.txtSyncStatus.setMouseTracking(False)
        self.txtSyncStatus.setText(_fromUtf8(""))
        self.txtSyncStatus.setFrame(False)
        self.txtSyncStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSyncStatus.setReadOnly(True)
        self.txtSyncStatus.setObjectName(_fromUtf8("txtSyncStatus"))
        self.gridLayout_4.addWidget(self.txtSyncStatus, 3, 3, 1, 1)
        self.progSync = QtGui.QProgressBar(self.frameSyncExec)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progSync.sizePolicy().hasHeightForWidth())
        self.progSync.setSizePolicy(sizePolicy)
        self.progSync.setProperty("value", 0)
        self.progSync.setObjectName(_fromUtf8("progSync"))
        self.gridLayout_4.addWidget(self.progSync, 3, 0, 1, 3)
        self.gridLayout.addWidget(self.frameSyncExec, 5, 0, 1, 2)
        self.frameAnalog = QtGui.QFrame(Interface)
        self.frameAnalog.setEnabled(True)
        self.frameAnalog.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameAnalog.setFrameShadow(QtGui.QFrame.Raised)
        self.frameAnalog.setObjectName(_fromUtf8("frameAnalog"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frameAnalog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.txtAIValue = QtGui.QLineEdit(self.frameAnalog)
        self.txtAIValue.setEnabled(True)
        self.txtAIValue.setMouseTracking(False)
        self.txtAIValue.setToolTip(_fromUtf8("Valor convertido pela entrada analógica"))
        self.txtAIValue.setFrame(False)
        self.txtAIValue.setAlignment(QtCore.Qt.AlignCenter)
        self.txtAIValue.setReadOnly(True)
        self.txtAIValue.setObjectName(_fromUtf8("txtAIValue"))
        self.gridLayout_2.addWidget(self.txtAIValue, 2, 4, 1, 2)
        self.btAIRead = QtGui.QPushButton(self.frameAnalog)
        self.btAIRead.setMaximumSize(QtCore.QSize(20, 16777215))
        self.btAIRead.setToolTip(_fromUtf8("Ler entrada analógica"))
        self.btAIRead.setObjectName(_fromUtf8("btAIRead"))
        self.gridLayout_2.addWidget(self.btAIRead, 2, 6, 1, 1)
        self.btAOWrite = QtGui.QPushButton(self.frameAnalog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btAOWrite.sizePolicy().hasHeightForWidth())
        self.btAOWrite.setSizePolicy(sizePolicy)
        self.btAOWrite.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btAOWrite.setToolTip(_fromUtf8("Iniciar a conversão da saída analógica"))
        self.btAOWrite.setObjectName(_fromUtf8("btAOWrite"))
        self.gridLayout_2.addWidget(self.btAOWrite, 4, 5, 1, 1)
        self.txtAOValue = QtGui.QLineEdit(self.frameAnalog)
        self.txtAOValue.setEnabled(True)
        self.txtAOValue.setMouseTracking(False)
        self.txtAOValue.setToolTip(_fromUtf8("Valor a ser convertido pela saída analógica"))
        self.txtAOValue.setFrame(True)
        self.txtAOValue.setAlignment(QtCore.Qt.AlignCenter)
        self.txtAOValue.setReadOnly(False)
        self.txtAOValue.setObjectName(_fromUtf8("txtAOValue"))
        self.gridLayout_2.addWidget(self.txtAOValue, 4, 4, 1, 1)
        self.btAORead = QtGui.QPushButton(self.frameAnalog)
        self.btAORead.setMaximumSize(QtCore.QSize(20, 16777215))
        self.btAORead.setToolTip(_fromUtf8("Atualizar com o último valor escrito na saída analógica"))
        self.btAORead.setObjectName(_fromUtf8("btAORead"))
        self.gridLayout_2.addWidget(self.btAORead, 4, 6, 1, 1)
        self.lblAO = QtGui.QLabel(self.frameAnalog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblAO.setFont(font)
        self.lblAO.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAO.setObjectName(_fromUtf8("lblAO"))
        self.gridLayout_2.addWidget(self.lblAO, 3, 4, 1, 3)
        self.lblAI = QtGui.QLabel(self.frameAnalog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblAI.setFont(font)
        self.lblAI.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAI.setObjectName(_fromUtf8("lblAI"))
        self.gridLayout_2.addWidget(self.lblAI, 1, 4, 1, 3)
        self.gridLayout.addWidget(self.frameAnalog, 2, 0, 1, 1)
        self.frameSyncGen = QtGui.QFrame(Interface)
        self.frameSyncGen.setEnabled(True)
        self.frameSyncGen.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameSyncGen.setFrameShadow(QtGui.QFrame.Raised)
        self.frameSyncGen.setObjectName(_fromUtf8("frameSyncGen"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frameSyncGen)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblSyncGen = QtGui.QLabel(self.frameSyncGen)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSyncGen.setFont(font)
        self.lblSyncGen.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSyncGen.setObjectName(_fromUtf8("lblSyncGen"))
        self.verticalLayout.addWidget(self.lblSyncGen)
        self.tabGen = QtGui.QTabWidget(self.frameSyncGen)
        self.tabGen.setTabPosition(QtGui.QTabWidget.North)
        self.tabGen.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabGen.setElideMode(QtCore.Qt.ElideNone)
        self.tabGen.setObjectName(_fromUtf8("tabGen"))
        self.tabGenPer = QtGui.QWidget()
        self.tabGenPer.setObjectName(_fromUtf8("tabGenPer"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabGenPer)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.txtGenPerPhase = QtGui.QLineEdit(self.tabGenPer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGenPerPhase.sizePolicy().hasHeightForWidth())
        self.txtGenPerPhase.setSizePolicy(sizePolicy)
        self.txtGenPerPhase.setAlignment(QtCore.Qt.AlignCenter)
        self.txtGenPerPhase.setObjectName(_fromUtf8("txtGenPerPhase"))
        self.gridLayout_6.addWidget(self.txtGenPerPhase, 1, 4, 1, 1)
        self.lblGenPerPhase = QtGui.QLabel(self.tabGenPer)
        self.lblGenPerPhase.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGenPerPhase.setObjectName(_fromUtf8("lblGenPerPhase"))
        self.gridLayout_6.addWidget(self.lblGenPerPhase, 0, 4, 1, 1)
        self.lblGenPerFreq = QtGui.QLabel(self.tabGenPer)
        self.lblGenPerFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGenPerFreq.setObjectName(_fromUtf8("lblGenPerFreq"))
        self.gridLayout_6.addWidget(self.lblGenPerFreq, 0, 2, 1, 1)
        self.txtGenPerFreq = QtGui.QLineEdit(self.tabGenPer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGenPerFreq.sizePolicy().hasHeightForWidth())
        self.txtGenPerFreq.setSizePolicy(sizePolicy)
        self.txtGenPerFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.txtGenPerFreq.setObjectName(_fromUtf8("txtGenPerFreq"))
        self.gridLayout_6.addWidget(self.txtGenPerFreq, 1, 2, 1, 1)
        self.lblGenPerType = QtGui.QLabel(self.tabGenPer)
        self.lblGenPerType.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGenPerType.setObjectName(_fromUtf8("lblGenPerType"))
        self.gridLayout_6.addWidget(self.lblGenPerType, 0, 0, 1, 1)
        self.cbGenPerType = QtGui.QComboBox(self.tabGenPer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbGenPerType.sizePolicy().hasHeightForWidth())
        self.cbGenPerType.setSizePolicy(sizePolicy)
        self.cbGenPerType.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.cbGenPerType.setObjectName(_fromUtf8("cbGenPerType"))
        self.cbGenPerType.addItem(_fromUtf8(""))
        self.cbGenPerType.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.cbGenPerType, 1, 0, 1, 1)
        self.txtGenPerAmpl = QtGui.QLineEdit(self.tabGenPer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGenPerAmpl.sizePolicy().hasHeightForWidth())
        self.txtGenPerAmpl.setSizePolicy(sizePolicy)
        self.txtGenPerAmpl.setToolTip(_fromUtf8("Apenas um teste"))
        self.txtGenPerAmpl.setAlignment(QtCore.Qt.AlignCenter)
        self.txtGenPerAmpl.setObjectName(_fromUtf8("txtGenPerAmpl"))
        self.gridLayout_6.addWidget(self.txtGenPerAmpl, 1, 1, 1, 1)
        self.lblGenPerAmpl = QtGui.QLabel(self.tabGenPer)
        self.lblGenPerAmpl.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGenPerAmpl.setObjectName(_fromUtf8("lblGenPerAmpl"))
        self.gridLayout_6.addWidget(self.lblGenPerAmpl, 0, 1, 1, 1)
        self.txtGenPerOff = QtGui.QLineEdit(self.tabGenPer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGenPerOff.sizePolicy().hasHeightForWidth())
        self.txtGenPerOff.setSizePolicy(sizePolicy)
        self.txtGenPerOff.setAlignment(QtCore.Qt.AlignCenter)
        self.txtGenPerOff.setObjectName(_fromUtf8("txtGenPerOff"))
        self.gridLayout_6.addWidget(self.txtGenPerOff, 1, 3, 1, 1)
        self.lblGenPerOffset = QtGui.QLabel(self.tabGenPer)
        self.lblGenPerOffset.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGenPerOffset.setObjectName(_fromUtf8("lblGenPerOffset"))
        self.gridLayout_6.addWidget(self.lblGenPerOffset, 0, 3, 1, 1)
        self.tabGen.addTab(self.tabGenPer, _fromUtf8(""))
        self.tabGenTrap = QtGui.QWidget()
        self.tabGenTrap.setObjectName(_fromUtf8("tabGenTrap"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabGenTrap)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.txtGenTrapRiseTime = QtGui.QLineEdit(self.tabGenTrap)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGenTrapRiseTime.sizePolicy().hasHeightForWidth())
        self.txtGenTrapRiseTime.setSizePolicy(sizePolicy)
        self.txtGenTrapRiseTime.setAlignment(QtCore.Qt.AlignCenter)
        self.txtGenTrapRiseTime.setObjectName(_fromUtf8("txtGenTrapRiseTime"))
        self.gridLayout_7.addWidget(self.txtGenTrapRiseTime, 1, 2, 1, 1)
        self.lblGenTrapBaseV = QtGui.QLabel(self.tabGenTrap)
        self.lblGenTrapBaseV.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGenTrapBaseV.setObjectName(_fromUtf8("lblGenTrapBaseV"))
        self.gridLayout_7.addWidget(self.lblGenTrapBaseV, 0, 0, 1, 1)
        self.lblGenTrapClimbTime = QtGui.QLabel(self.tabGenTrap)
        self.lblGenTrapClimbTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGenTrapClimbTime.setObjectName(_fromUtf8("lblGenTrapClimbTime"))
        self.gridLayout_7.addWidget(self.lblGenTrapClimbTime, 0, 2, 1, 1)
        self.txtGenTrapTopV = QtGui.QLineEdit(self.tabGenTrap)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGenTrapTopV.sizePolicy().hasHeightForWidth())
        self.txtGenTrapTopV.setSizePolicy(sizePolicy)
        self.txtGenTrapTopV.setAlignment(QtCore.Qt.AlignCenter)
        self.txtGenTrapTopV.setObjectName(_fromUtf8("txtGenTrapTopV"))
        self.gridLayout_7.addWidget(self.txtGenTrapTopV, 1, 1, 1, 1)
        self.txtGenTrapPlateauTime = QtGui.QLineEdit(self.tabGenTrap)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGenTrapPlateauTime.sizePolicy().hasHeightForWidth())
        self.txtGenTrapPlateauTime.setSizePolicy(sizePolicy)
        self.txtGenTrapPlateauTime.setAlignment(QtCore.Qt.AlignCenter)
        self.txtGenTrapPlateauTime.setObjectName(_fromUtf8("txtGenTrapPlateauTime"))
        self.gridLayout_7.addWidget(self.txtGenTrapPlateauTime, 1, 3, 1, 1)
        self.lblGenTrapTopV = QtGui.QLabel(self.tabGenTrap)
        self.lblGenTrapTopV.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGenTrapTopV.setObjectName(_fromUtf8("lblGenTrapTopV"))
        self.gridLayout_7.addWidget(self.lblGenTrapTopV, 0, 1, 1, 1)
        self.txtGenTrapBaseV = QtGui.QLineEdit(self.tabGenTrap)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGenTrapBaseV.sizePolicy().hasHeightForWidth())
        self.txtGenTrapBaseV.setSizePolicy(sizePolicy)
        self.txtGenTrapBaseV.setAlignment(QtCore.Qt.AlignCenter)
        self.txtGenTrapBaseV.setObjectName(_fromUtf8("txtGenTrapBaseV"))
        self.gridLayout_7.addWidget(self.txtGenTrapBaseV, 1, 0, 1, 1)
        self.lblGenTrapTopTime = QtGui.QLabel(self.tabGenTrap)
        self.lblGenTrapTopTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGenTrapTopTime.setObjectName(_fromUtf8("lblGenTrapTopTime"))
        self.gridLayout_7.addWidget(self.lblGenTrapTopTime, 0, 3, 1, 1)
        self.lblGenTrapDescendTime = QtGui.QLabel(self.tabGenTrap)
        self.lblGenTrapDescendTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGenTrapDescendTime.setObjectName(_fromUtf8("lblGenTrapDescendTime"))
        self.gridLayout_7.addWidget(self.lblGenTrapDescendTime, 0, 4, 1, 1)
        self.txtGenTrapFallTime = QtGui.QLineEdit(self.tabGenTrap)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGenTrapFallTime.sizePolicy().hasHeightForWidth())
        self.txtGenTrapFallTime.setSizePolicy(sizePolicy)
        self.txtGenTrapFallTime.setMinimumSize(QtCore.QSize(80, 0))
        self.txtGenTrapFallTime.setFrame(False)
        self.txtGenTrapFallTime.setAlignment(QtCore.Qt.AlignCenter)
        self.txtGenTrapFallTime.setReadOnly(True)
        self.txtGenTrapFallTime.setObjectName(_fromUtf8("txtGenTrapFallTime"))
        self.gridLayout_7.addWidget(self.txtGenTrapFallTime, 1, 4, 1, 1)
        self.tabGen.addTab(self.tabGenTrap, _fromUtf8(""))
        self.tabGenLin = QtGui.QWidget()
        self.tabGenLin.setObjectName(_fromUtf8("tabGenLin"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tabGenLin)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.txtGenLinEndV = QtGui.QLineEdit(self.tabGenLin)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGenLinEndV.sizePolicy().hasHeightForWidth())
        self.txtGenLinEndV.setSizePolicy(sizePolicy)
        self.txtGenLinEndV.setAlignment(QtCore.Qt.AlignCenter)
        self.txtGenLinEndV.setObjectName(_fromUtf8("txtGenLinEndV"))
        self.gridLayout_8.addWidget(self.txtGenLinEndV, 1, 1, 1, 1)
        self.txtGenLinStartV = QtGui.QLineEdit(self.tabGenLin)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGenLinStartV.sizePolicy().hasHeightForWidth())
        self.txtGenLinStartV.setSizePolicy(sizePolicy)
        self.txtGenLinStartV.setAlignment(QtCore.Qt.AlignCenter)
        self.txtGenLinStartV.setObjectName(_fromUtf8("txtGenLinStartV"))
        self.gridLayout_8.addWidget(self.txtGenLinStartV, 1, 0, 1, 1)
        self.lblGenLinStartV = QtGui.QLabel(self.tabGenLin)
        self.lblGenLinStartV.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGenLinStartV.setObjectName(_fromUtf8("lblGenLinStartV"))
        self.gridLayout_8.addWidget(self.lblGenLinStartV, 0, 0, 1, 1)
        self.lblGenLinEndV = QtGui.QLabel(self.tabGenLin)
        self.lblGenLinEndV.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGenLinEndV.setObjectName(_fromUtf8("lblGenLinEndV"))
        self.gridLayout_8.addWidget(self.lblGenLinEndV, 0, 1, 1, 1)
        self.tabGen.addTab(self.tabGenLin, _fromUtf8(""))
        self.tabGenFile = QtGui.QWidget()
        self.tabGenFile.setObjectName(_fromUtf8("tabGenFile"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabGenFile)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblGenFile = QtGui.QLabel(self.tabGenFile)
        self.lblGenFile.setObjectName(_fromUtf8("lblGenFile"))
        self.horizontalLayout_2.addWidget(self.lblGenFile)
        self.txtGenFilePath = QtGui.QLineEdit(self.tabGenFile)
        self.txtGenFilePath.setObjectName(_fromUtf8("txtGenFilePath"))
        self.horizontalLayout_2.addWidget(self.txtGenFilePath)
        self.btGenFileSelect = QtGui.QPushButton(self.tabGenFile)
        self.btGenFileSelect.setObjectName(_fromUtf8("btGenFileSelect"))
        self.horizontalLayout_2.addWidget(self.btGenFileSelect)
        self.tabGen.addTab(self.tabGenFile, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabGen)
        self.btSyncGenSend = QtGui.QPushButton(self.frameSyncGen)
        self.btSyncGenSend.setObjectName(_fromUtf8("btSyncGenSend"))
        self.verticalLayout.addWidget(self.btSyncGenSend)
        self.gridLayout.addWidget(self.frameSyncGen, 4, 0, 1, 2)
        self.frameConn = QtGui.QFrame(Interface)
        self.frameConn.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameConn.setFrameShadow(QtGui.QFrame.Raised)
        self.frameConn.setObjectName(_fromUtf8("frameConn"))
        self.gridLayout_16 = QtGui.QGridLayout(self.frameConn)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.btConnect = QtGui.QPushButton(self.frameConn)
        self.btConnect.setToolTip(_fromUtf8("Conectar/Desconectar à PUC"))
        self.btConnect.setObjectName(_fromUtf8("btConnect"))
        self.gridLayout_16.addWidget(self.btConnect, 0, 6, 1, 1)
        self.spinSerialAddress = QtGui.QSpinBox(self.frameConn)
        self.spinSerialAddress.setToolTip(_fromUtf8("Endereço configurado nos jumpers da PUC"))
        self.spinSerialAddress.setMinimum(1)
        self.spinSerialAddress.setMaximum(31)
        self.spinSerialAddress.setProperty("value", 8)
        self.spinSerialAddress.setObjectName(_fromUtf8("spinSerialAddress"))
        self.gridLayout_16.addWidget(self.spinSerialAddress, 0, 5, 1, 1)
        self.lblSerialAddress = QtGui.QLabel(self.frameConn)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSerialAddress.sizePolicy().hasHeightForWidth())
        self.lblSerialAddress.setSizePolicy(sizePolicy)
        self.lblSerialAddress.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSerialAddress.setObjectName(_fromUtf8("lblSerialAddress"))
        self.gridLayout_16.addWidget(self.lblSerialAddress, 0, 4, 1, 1)
        self.lblSerialPort = QtGui.QLabel(self.frameConn)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSerialPort.sizePolicy().hasHeightForWidth())
        self.lblSerialPort.setSizePolicy(sizePolicy)
        self.lblSerialPort.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSerialPort.setObjectName(_fromUtf8("lblSerialPort"))
        self.gridLayout_16.addWidget(self.lblSerialPort, 0, 0, 1, 1)
        self.txtSerialPort = QtGui.QLineEdit(self.frameConn)
        self.txtSerialPort.setToolTip(_fromUtf8("Porta serial a ser usada.\n"
"* Linux: /dev/tty*\n"
"* Windows: COM*"))
        self.txtSerialPort.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txtSerialPort.setObjectName(_fromUtf8("txtSerialPort"))
        self.gridLayout_16.addWidget(self.txtSerialPort, 0, 1, 1, 2)
        self.btReset = QtGui.QPushButton(self.frameConn)
        self.btReset.setToolTip(_fromUtf8("Reset na PUC. Equivale a um ciclo de energia."))
        self.btReset.setObjectName(_fromUtf8("btReset"))
        self.gridLayout_16.addWidget(self.btReset, 0, 7, 1, 1)
        self.gridLayout.addWidget(self.frameConn, 0, 0, 1, 2)
        self.frameSyncCfg = QtGui.QFrame(Interface)
        self.frameSyncCfg.setEnabled(True)
        self.frameSyncCfg.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameSyncCfg.setFrameShadow(QtGui.QFrame.Raised)
        self.frameSyncCfg.setObjectName(_fromUtf8("frameSyncCfg"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frameSyncCfg)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cbSyncPtSize = QtGui.QComboBox(self.frameSyncCfg)
        self.cbSyncPtSize.setToolTip(_fromUtf8("Precisão dos pontos das curvas:\n"
"* 16-bits: cada ponto ocupará 2 bytes\n"
"* 18-bits: cada ponto ocupará 4 bytes"))
        self.cbSyncPtSize.setModelColumn(0)
        self.cbSyncPtSize.setObjectName(_fromUtf8("cbSyncPtSize"))
        self.cbSyncPtSize.addItem(_fromUtf8(""))
        self.cbSyncPtSize.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cbSyncPtSize, 1, 3, 1, 1)
        self.lblSyncClk = QtGui.QLabel(self.frameSyncCfg)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblSyncClk.setFont(font)
        self.lblSyncClk.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSyncClk.setObjectName(_fromUtf8("lblSyncClk"))
        self.gridLayout_3.addWidget(self.lblSyncClk, 2, 0, 1, 1)
        self.lblSyncClkPulseBit = QtGui.QLabel(self.frameSyncCfg)
        self.lblSyncClkPulseBit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSyncClkPulseBit.setObjectName(_fromUtf8("lblSyncClkPulseBit"))
        self.gridLayout_3.addWidget(self.lblSyncClkPulseBit, 4, 2, 1, 1)
        self.lblSyncConfig = QtGui.QLabel(self.frameSyncCfg)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSyncConfig.setFont(font)
        self.lblSyncConfig.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSyncConfig.setObjectName(_fromUtf8("lblSyncConfig"))
        self.gridLayout_3.addWidget(self.lblSyncConfig, 0, 0, 1, 4)
        self.lblSyncClkOutBit = QtGui.QLabel(self.frameSyncCfg)
        self.lblSyncClkOutBit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSyncClkOutBit.setObjectName(_fromUtf8("lblSyncClkOutBit"))
        self.gridLayout_3.addWidget(self.lblSyncClkOutBit, 3, 2, 1, 1)
        self.lblSyncClkFreq = QtGui.QLabel(self.frameSyncCfg)
        self.lblSyncClkFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSyncClkFreq.setObjectName(_fromUtf8("lblSyncClkFreq"))
        self.gridLayout_3.addWidget(self.lblSyncClkFreq, 2, 2, 1, 1)
        self.cbSyncClkPulseBit = QtGui.QComboBox(self.frameSyncCfg)
        self.cbSyncClkPulseBit.setToolTip(_fromUtf8("Qual bit da saída digital deve ser usado para se gerar um pulso ao fim de um procedimento síncrono"))
        self.cbSyncClkPulseBit.setObjectName(_fromUtf8("cbSyncClkPulseBit"))
        self.cbSyncClkPulseBit.addItem(_fromUtf8(""))
        self.cbSyncClkPulseBit.addItem(_fromUtf8(""))
        self.cbSyncClkPulseBit.addItem(_fromUtf8(""))
        self.cbSyncClkPulseBit.addItem(_fromUtf8(""))
        self.cbSyncClkPulseBit.addItem(_fromUtf8(""))
        self.cbSyncClkPulseBit.addItem(_fromUtf8(""))
        self.cbSyncClkPulseBit.addItem(_fromUtf8(""))
        self.cbSyncClkPulseBit.addItem(_fromUtf8(""))
        self.cbSyncClkPulseBit.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cbSyncClkPulseBit, 4, 3, 1, 1)
        self.lblSyncClkDiv = QtGui.QLabel(self.frameSyncCfg)
        self.lblSyncClkDiv.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSyncClkDiv.setObjectName(_fromUtf8("lblSyncClkDiv"))
        self.gridLayout_3.addWidget(self.lblSyncClkDiv, 3, 0, 1, 1)
        self.spinSyncNPts = QtGui.QSpinBox(self.frameSyncCfg)
        self.spinSyncNPts.setToolTip(_fromUtf8("Número de pontos a serem lidos/escritos para/da memória.\n"
"As memórias tem tamanho de 128 kB, assim, o máximo de pontos depende do tamanho de cada ponto (de acordo com o campo Precisão)"))
        self.spinSyncNPts.setMinimum(1)
        self.spinSyncNPts.setMaximum(65536)
        self.spinSyncNPts.setProperty("value", 65536)
        self.spinSyncNPts.setObjectName(_fromUtf8("spinSyncNPts"))
        self.gridLayout_3.addWidget(self.spinSyncNPts, 4, 1, 1, 1)
        self.cbSyncClkSrc = QtGui.QComboBox(self.frameSyncCfg)
        self.cbSyncClkSrc.setToolTip(_fromUtf8("Fonte de clock a ser usada no procedimento síncrono\n"
"* Timer: Será usado um Timer interno do processador da PUC\n"
"* Externo: Uma fonte de clock externa deve ser conectada à PUC\n"
"* Serial: Os pulsos de clock devem ser gerados manualmente com o botão Passo"))
        self.cbSyncClkSrc.setObjectName(_fromUtf8("cbSyncClkSrc"))
        self.cbSyncClkSrc.addItem(_fromUtf8(""))
        self.cbSyncClkSrc.addItem(_fromUtf8(""))
        self.cbSyncClkSrc.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cbSyncClkSrc, 2, 1, 1, 1)
        self.cbSyncClkOutBit = QtGui.QComboBox(self.frameSyncCfg)
        self.cbSyncClkOutBit.setToolTip(_fromUtf8("Qual bit da saída digital deve ser usado para se externar o clock"))
        self.cbSyncClkOutBit.setObjectName(_fromUtf8("cbSyncClkOutBit"))
        self.cbSyncClkOutBit.addItem(_fromUtf8(""))
        self.cbSyncClkOutBit.addItem(_fromUtf8(""))
        self.cbSyncClkOutBit.addItem(_fromUtf8(""))
        self.cbSyncClkOutBit.addItem(_fromUtf8(""))
        self.cbSyncClkOutBit.addItem(_fromUtf8(""))
        self.cbSyncClkOutBit.addItem(_fromUtf8(""))
        self.cbSyncClkOutBit.addItem(_fromUtf8(""))
        self.cbSyncClkOutBit.addItem(_fromUtf8(""))
        self.cbSyncClkOutBit.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cbSyncClkOutBit, 3, 3, 1, 1)
        self.chkSyncInEn = QtGui.QCheckBox(self.frameSyncCfg)
        self.chkSyncInEn.setToolTip(_fromUtf8("A cada passo, gravar a entrada analógica na memória RAM"))
        self.chkSyncInEn.setChecked(True)
        self.chkSyncInEn.setObjectName(_fromUtf8("chkSyncInEn"))
        self.gridLayout_3.addWidget(self.chkSyncInEn, 1, 0, 1, 1)
        self.spinSyncClkDiv = QtGui.QSpinBox(self.frameSyncCfg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinSyncClkDiv.sizePolicy().hasHeightForWidth())
        self.spinSyncClkDiv.setSizePolicy(sizePolicy)
        self.spinSyncClkDiv.setToolTip(_fromUtf8("Divisor a ser usado para se determinar a frequência do Timer.\n"
"A fórmula é:\n"
"Frequência = 60kHz/(1+Divisor)"))
        self.spinSyncClkDiv.setMinimum(1)
        self.spinSyncClkDiv.setMaximum(65535)
        self.spinSyncClkDiv.setObjectName(_fromUtf8("spinSyncClkDiv"))
        self.gridLayout_3.addWidget(self.spinSyncClkDiv, 3, 1, 1, 1)
        self.lblSyncInPtSize = QtGui.QLabel(self.frameSyncCfg)
        self.lblSyncInPtSize.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSyncInPtSize.setObjectName(_fromUtf8("lblSyncInPtSize"))
        self.gridLayout_3.addWidget(self.lblSyncInPtSize, 1, 2, 1, 1)
        self.txtSyncFreq = QtGui.QLineEdit(self.frameSyncCfg)
        self.txtSyncFreq.setEnabled(True)
        self.txtSyncFreq.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txtSyncFreq.setToolTip(_fromUtf8("Frequência com a qual os pontos serão expelidos/capturados.\n"
"Seu significado depende do valor selecionado em Fonte Clock:\n"
"* Timer: Indica a frequência do Timer de acordo com o Divisor (somente leitura)\n"
"* Externo: Deve-se indicar qual a frequência externa conectada\n"
"* Serial: Não há frequência fixa; os pulsos serão gerados pelo botão Passo"))
        self.txtSyncFreq.setText(_fromUtf8(""))
        self.txtSyncFreq.setFrame(True)
        self.txtSyncFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSyncFreq.setObjectName(_fromUtf8("txtSyncFreq"))
        self.gridLayout_3.addWidget(self.txtSyncFreq, 2, 3, 1, 1)
        self.lblSyncInNPts = QtGui.QLabel(self.frameSyncCfg)
        self.lblSyncInNPts.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSyncInNPts.setObjectName(_fromUtf8("lblSyncInNPts"))
        self.gridLayout_3.addWidget(self.lblSyncInNPts, 4, 0, 1, 1)
        self.chkSyncOutEn = QtGui.QCheckBox(self.frameSyncCfg)
        self.chkSyncOutEn.setChecked(True)
        self.chkSyncOutEn.setObjectName(_fromUtf8("chkSyncOutEn"))
        self.gridLayout_3.addWidget(self.chkSyncOutEn, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frameSyncCfg, 3, 0, 1, 2)
        self.txtStatus = QtGui.QLineEdit(Interface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtStatus.sizePolicy().hasHeightForWidth())
        self.txtStatus.setSizePolicy(sizePolicy)
        self.txtStatus.setToolTip(_fromUtf8("Status"))
        self.txtStatus.setFrame(False)
        self.txtStatus.setReadOnly(True)
        self.txtStatus.setObjectName(_fromUtf8("txtStatus"))
        self.gridLayout.addWidget(self.txtStatus, 1, 0, 1, 2)
        self.frameDigital = QtGui.QFrame(Interface)
        self.frameDigital.setEnabled(True)
        self.frameDigital.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameDigital.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDigital.setObjectName(_fromUtf8("frameDigital"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frameDigital)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frameDOBoxes = QtGui.QFrame(self.frameDigital)
        self.frameDOBoxes.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameDOBoxes.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDOBoxes.setObjectName(_fromUtf8("frameDOBoxes"))
        self.gridLayout_14 = QtGui.QGridLayout(self.frameDOBoxes)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.chkDO6 = QtGui.QCheckBox(self.frameDOBoxes)
        self.chkDO6.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDO6.sizePolicy().hasHeightForWidth())
        self.chkDO6.setSizePolicy(sizePolicy)
        self.chkDO6.setToolTip(_fromUtf8("Bit 6"))
        self.chkDO6.setText(_fromUtf8(""))
        self.chkDO6.setCheckable(True)
        self.chkDO6.setObjectName(_fromUtf8("chkDO6"))
        self.gridLayout_14.addWidget(self.chkDO6, 1, 2, 1, 1)
        self.lblDOLess = QtGui.QLabel(self.frameDOBoxes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDOLess.sizePolicy().hasHeightForWidth())
        self.lblDOLess.setSizePolicy(sizePolicy)
        self.lblDOLess.setObjectName(_fromUtf8("lblDOLess"))
        self.gridLayout_14.addWidget(self.lblDOLess, 1, 9, 1, 1)
        self.lblDOMost = QtGui.QLabel(self.frameDOBoxes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDOMost.sizePolicy().hasHeightForWidth())
        self.lblDOMost.setSizePolicy(sizePolicy)
        self.lblDOMost.setObjectName(_fromUtf8("lblDOMost"))
        self.gridLayout_14.addWidget(self.lblDOMost, 1, 0, 1, 1)
        self.chkDO3 = QtGui.QCheckBox(self.frameDOBoxes)
        self.chkDO3.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDO3.sizePolicy().hasHeightForWidth())
        self.chkDO3.setSizePolicy(sizePolicy)
        self.chkDO3.setToolTip(_fromUtf8("Bit 3"))
        self.chkDO3.setText(_fromUtf8(""))
        self.chkDO3.setCheckable(True)
        self.chkDO3.setObjectName(_fromUtf8("chkDO3"))
        self.gridLayout_14.addWidget(self.chkDO3, 1, 5, 1, 1)
        self.chkDO1 = QtGui.QCheckBox(self.frameDOBoxes)
        self.chkDO1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDO1.sizePolicy().hasHeightForWidth())
        self.chkDO1.setSizePolicy(sizePolicy)
        self.chkDO1.setToolTip(_fromUtf8("Bit 1"))
        self.chkDO1.setText(_fromUtf8(""))
        self.chkDO1.setCheckable(True)
        self.chkDO1.setObjectName(_fromUtf8("chkDO1"))
        self.gridLayout_14.addWidget(self.chkDO1, 1, 7, 1, 1)
        self.chkDO2 = QtGui.QCheckBox(self.frameDOBoxes)
        self.chkDO2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDO2.sizePolicy().hasHeightForWidth())
        self.chkDO2.setSizePolicy(sizePolicy)
        self.chkDO2.setToolTip(_fromUtf8("Bit 2"))
        self.chkDO2.setText(_fromUtf8(""))
        self.chkDO2.setCheckable(True)
        self.chkDO2.setObjectName(_fromUtf8("chkDO2"))
        self.gridLayout_14.addWidget(self.chkDO2, 1, 6, 1, 1)
        self.chkDO5 = QtGui.QCheckBox(self.frameDOBoxes)
        self.chkDO5.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDO5.sizePolicy().hasHeightForWidth())
        self.chkDO5.setSizePolicy(sizePolicy)
        self.chkDO5.setToolTip(_fromUtf8("Bit 5"))
        self.chkDO5.setText(_fromUtf8(""))
        self.chkDO5.setCheckable(True)
        self.chkDO5.setObjectName(_fromUtf8("chkDO5"))
        self.gridLayout_14.addWidget(self.chkDO5, 1, 3, 1, 1)
        self.chkDO7 = QtGui.QCheckBox(self.frameDOBoxes)
        self.chkDO7.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDO7.sizePolicy().hasHeightForWidth())
        self.chkDO7.setSizePolicy(sizePolicy)
        self.chkDO7.setToolTip(_fromUtf8("Bit 7 (mais significativo)"))
        self.chkDO7.setText(_fromUtf8(""))
        self.chkDO7.setCheckable(True)
        self.chkDO7.setAutoRepeat(False)
        self.chkDO7.setTristate(False)
        self.chkDO7.setObjectName(_fromUtf8("chkDO7"))
        self.gridLayout_14.addWidget(self.chkDO7, 1, 1, 1, 1)
        self.chkDO0 = QtGui.QCheckBox(self.frameDOBoxes)
        self.chkDO0.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDO0.sizePolicy().hasHeightForWidth())
        self.chkDO0.setSizePolicy(sizePolicy)
        self.chkDO0.setToolTip(_fromUtf8("Bit 0 (menos significativo)"))
        self.chkDO0.setText(_fromUtf8(""))
        self.chkDO0.setCheckable(True)
        self.chkDO0.setObjectName(_fromUtf8("chkDO0"))
        self.gridLayout_14.addWidget(self.chkDO0, 1, 8, 1, 1)
        self.chkDO4 = QtGui.QCheckBox(self.frameDOBoxes)
        self.chkDO4.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDO4.sizePolicy().hasHeightForWidth())
        self.chkDO4.setSizePolicy(sizePolicy)
        self.chkDO4.setToolTip(_fromUtf8("Bit 4"))
        self.chkDO4.setText(_fromUtf8(""))
        self.chkDO4.setCheckable(True)
        self.chkDO4.setObjectName(_fromUtf8("chkDO4"))
        self.gridLayout_14.addWidget(self.chkDO4, 1, 4, 1, 1)
        self.gridLayout_5.addWidget(self.frameDOBoxes, 3, 0, 1, 1)
        self.lblDO = QtGui.QLabel(self.frameDigital)
        self.lblDO.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblDO.setFont(font)
        self.lblDO.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDO.setObjectName(_fromUtf8("lblDO"))
        self.gridLayout_5.addWidget(self.lblDO, 2, 0, 1, 2)
        self.btDORead = QtGui.QPushButton(self.frameDigital)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btDORead.sizePolicy().hasHeightForWidth())
        self.btDORead.setSizePolicy(sizePolicy)
        self.btDORead.setMaximumSize(QtCore.QSize(20, 16777215))
        self.btDORead.setObjectName(_fromUtf8("btDORead"))
        self.gridLayout_5.addWidget(self.btDORead, 3, 1, 1, 1)
        self.frameDIBoxes = QtGui.QFrame(self.frameDigital)
        self.frameDIBoxes.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameDIBoxes.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDIBoxes.setObjectName(_fromUtf8("frameDIBoxes"))
        self.gridLayout_13 = QtGui.QGridLayout(self.frameDIBoxes)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.chkDI6 = QtGui.QCheckBox(self.frameDIBoxes)
        self.chkDI6.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDI6.sizePolicy().hasHeightForWidth())
        self.chkDI6.setSizePolicy(sizePolicy)
        self.chkDI6.setToolTip(_fromUtf8("Bit 6"))
        self.chkDI6.setText(_fromUtf8(""))
        self.chkDI6.setCheckable(True)
        self.chkDI6.setObjectName(_fromUtf8("chkDI6"))
        self.gridLayout_13.addWidget(self.chkDI6, 1, 3, 1, 1)
        self.chkDI2 = QtGui.QCheckBox(self.frameDIBoxes)
        self.chkDI2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDI2.sizePolicy().hasHeightForWidth())
        self.chkDI2.setSizePolicy(sizePolicy)
        self.chkDI2.setToolTip(_fromUtf8("Bit 2"))
        self.chkDI2.setText(_fromUtf8(""))
        self.chkDI2.setCheckable(True)
        self.chkDI2.setObjectName(_fromUtf8("chkDI2"))
        self.gridLayout_13.addWidget(self.chkDI2, 1, 7, 1, 1)
        self.chkDI4 = QtGui.QCheckBox(self.frameDIBoxes)
        self.chkDI4.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDI4.sizePolicy().hasHeightForWidth())
        self.chkDI4.setSizePolicy(sizePolicy)
        self.chkDI4.setToolTip(_fromUtf8("Bit 4"))
        self.chkDI4.setText(_fromUtf8(""))
        self.chkDI4.setCheckable(True)
        self.chkDI4.setObjectName(_fromUtf8("chkDI4"))
        self.gridLayout_13.addWidget(self.chkDI4, 1, 5, 1, 1)
        self.chkDI1 = QtGui.QCheckBox(self.frameDIBoxes)
        self.chkDI1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDI1.sizePolicy().hasHeightForWidth())
        self.chkDI1.setSizePolicy(sizePolicy)
        self.chkDI1.setToolTip(_fromUtf8("Bit 1"))
        self.chkDI1.setText(_fromUtf8(""))
        self.chkDI1.setCheckable(True)
        self.chkDI1.setObjectName(_fromUtf8("chkDI1"))
        self.gridLayout_13.addWidget(self.chkDI1, 1, 8, 1, 1)
        self.lblDILeast = QtGui.QLabel(self.frameDIBoxes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDILeast.sizePolicy().hasHeightForWidth())
        self.lblDILeast.setSizePolicy(sizePolicy)
        self.lblDILeast.setObjectName(_fromUtf8("lblDILeast"))
        self.gridLayout_13.addWidget(self.lblDILeast, 1, 10, 1, 1)
        self.chkDI3 = QtGui.QCheckBox(self.frameDIBoxes)
        self.chkDI3.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDI3.sizePolicy().hasHeightForWidth())
        self.chkDI3.setSizePolicy(sizePolicy)
        self.chkDI3.setToolTip(_fromUtf8("Bit 3"))
        self.chkDI3.setText(_fromUtf8(""))
        self.chkDI3.setCheckable(True)
        self.chkDI3.setObjectName(_fromUtf8("chkDI3"))
        self.gridLayout_13.addWidget(self.chkDI3, 1, 6, 1, 1)
        self.lblDIMost = QtGui.QLabel(self.frameDIBoxes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDIMost.sizePolicy().hasHeightForWidth())
        self.lblDIMost.setSizePolicy(sizePolicy)
        self.lblDIMost.setObjectName(_fromUtf8("lblDIMost"))
        self.gridLayout_13.addWidget(self.lblDIMost, 1, 1, 1, 1)
        self.chkDI5 = QtGui.QCheckBox(self.frameDIBoxes)
        self.chkDI5.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDI5.sizePolicy().hasHeightForWidth())
        self.chkDI5.setSizePolicy(sizePolicy)
        self.chkDI5.setToolTip(_fromUtf8("Bit 5"))
        self.chkDI5.setText(_fromUtf8(""))
        self.chkDI5.setCheckable(True)
        self.chkDI5.setObjectName(_fromUtf8("chkDI5"))
        self.gridLayout_13.addWidget(self.chkDI5, 1, 4, 1, 1)
        self.chkDI7 = QtGui.QCheckBox(self.frameDIBoxes)
        self.chkDI7.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDI7.sizePolicy().hasHeightForWidth())
        self.chkDI7.setSizePolicy(sizePolicy)
        self.chkDI7.setToolTip(_fromUtf8("Bit 7 (mais significativo)"))
        self.chkDI7.setAutoFillBackground(False)
        self.chkDI7.setText(_fromUtf8(""))
        self.chkDI7.setCheckable(True)
        self.chkDI7.setAutoRepeat(False)
        self.chkDI7.setTristate(False)
        self.chkDI7.setObjectName(_fromUtf8("chkDI7"))
        self.gridLayout_13.addWidget(self.chkDI7, 1, 2, 1, 1)
        self.chkDI0 = QtGui.QCheckBox(self.frameDIBoxes)
        self.chkDI0.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDI0.sizePolicy().hasHeightForWidth())
        self.chkDI0.setSizePolicy(sizePolicy)
        self.chkDI0.setToolTip(_fromUtf8("Bit 0 (menos significativo)"))
        self.chkDI0.setText(_fromUtf8(""))
        self.chkDI0.setCheckable(True)
        self.chkDI0.setObjectName(_fromUtf8("chkDI0"))
        self.gridLayout_13.addWidget(self.chkDI0, 1, 9, 1, 1)
        self.gridLayout_5.addWidget(self.frameDIBoxes, 1, 0, 1, 1)
        self.btDIRead = QtGui.QPushButton(self.frameDigital)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btDIRead.sizePolicy().hasHeightForWidth())
        self.btDIRead.setSizePolicy(sizePolicy)
        self.btDIRead.setMaximumSize(QtCore.QSize(20, 16777215))
        self.btDIRead.setToolTip(_fromUtf8("Atualizar entrada digital"))
        self.btDIRead.setObjectName(_fromUtf8("btDIRead"))
        self.gridLayout_5.addWidget(self.btDIRead, 1, 1, 1, 1)
        self.lblDI = QtGui.QLabel(self.frameDigital)
        self.lblDI.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblDI.setFont(font)
        self.lblDI.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDI.setObjectName(_fromUtf8("lblDI"))
        self.gridLayout_5.addWidget(self.lblDI, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.frameDigital, 2, 1, 1, 1)
        self.frameReadCapture = QtGui.QFrame(Interface)
        self.frameReadCapture.setEnabled(True)
        self.frameReadCapture.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameReadCapture.setFrameShadow(QtGui.QFrame.Raised)
        self.frameReadCapture.setObjectName(_fromUtf8("frameReadCapture"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frameReadCapture)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.lblReadCaptureFile = QtGui.QLabel(self.frameReadCapture)
        self.lblReadCaptureFile.setObjectName(_fromUtf8("lblReadCaptureFile"))
        self.gridLayout_9.addWidget(self.lblReadCaptureFile, 1, 0, 1, 1)
        self.txtReadCaptureFilePath = QtGui.QLineEdit(self.frameReadCapture)
        self.txtReadCaptureFilePath.setObjectName(_fromUtf8("txtReadCaptureFilePath"))
        self.gridLayout_9.addWidget(self.txtReadCaptureFilePath, 1, 1, 1, 1)
        self.btReadCaptureFileChoose = QtGui.QPushButton(self.frameReadCapture)
        self.btReadCaptureFileChoose.setObjectName(_fromUtf8("btReadCaptureFileChoose"))
        self.gridLayout_9.addWidget(self.btReadCaptureFileChoose, 1, 2, 1, 1)
        self.btReadCapture = QtGui.QPushButton(self.frameReadCapture)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btReadCapture.sizePolicy().hasHeightForWidth())
        self.btReadCapture.setSizePolicy(sizePolicy)
        self.btReadCapture.setObjectName(_fromUtf8("btReadCapture"))
        self.gridLayout_9.addWidget(self.btReadCapture, 1, 3, 1, 1)
        self.lblReadCapture = QtGui.QLabel(self.frameReadCapture)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblReadCapture.setFont(font)
        self.lblReadCapture.setAlignment(QtCore.Qt.AlignCenter)
        self.lblReadCapture.setObjectName(_fromUtf8("lblReadCapture"))
        self.gridLayout_9.addWidget(self.lblReadCapture, 0, 0, 1, 4)
        self.gridLayout.addWidget(self.frameReadCapture, 6, 0, 1, 2)
        self.lblSerialAddress.setBuddy(self.txtSerialPort)
        self.lblSerialPort.setBuddy(self.txtSerialPort)

        self.retranslateUi(Interface)
        self.tabGen.setCurrentIndex(0)
        self.cbSyncPtSize.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Interface)

    def retranslateUi(self, Interface):
        Interface.setWindowTitle(_translate("Interface", "PUC Special Purpose", None))
        self.btSyncStop.setText(_translate("Interface", "■", None))
        self.lblSyncExec.setText(_translate("Interface", "Execução Síncrono", None))
        self.btSyncStep.setText(_translate("Interface", "Passo", None))
        self.btSyncStart.setText(_translate("Interface", "▶", None))
        self.btSyncPause.setText(_translate("Interface", "| |", None))
        self.txtAIValue.setText(_translate("Interface", "0.000", None))
        self.btAIRead.setText(_translate("Interface", "⟲", None))
        self.btAOWrite.setText(_translate("Interface", "Ajustar", None))
        self.txtAOValue.setText(_translate("Interface", "0.000", None))
        self.btAORead.setText(_translate("Interface", "⟲", None))
        self.lblAO.setText(_translate("Interface", "Saída Analógica (V)", None))
        self.lblAI.setText(_translate("Interface", "Entrada Analógica (V)", None))
        self.lblSyncGen.setText(_translate("Interface", "Gerador de Curvas", None))
        self.txtGenPerPhase.setText(_translate("Interface", "0", None))
        self.lblGenPerPhase.setText(_translate("Interface", "Fase (º)", None))
        self.lblGenPerFreq.setText(_translate("Interface", "Freq. (Hz)", None))
        self.txtGenPerFreq.setText(_translate("Interface", "10", None))
        self.lblGenPerType.setText(_translate("Interface", "Tipo", None))
        self.cbGenPerType.setItemText(0, _translate("Interface", "Senoidal", None))
        self.cbGenPerType.setItemText(1, _translate("Interface", "Quadrada", None))
        self.txtGenPerAmpl.setText(_translate("Interface", "10", None))
        self.lblGenPerAmpl.setText(_translate("Interface", "Ampl. (Vpp)", None))
        self.txtGenPerOff.setText(_translate("Interface", "0", None))
        self.lblGenPerOffset.setText(_translate("Interface", "Offset (V)", None))
        self.tabGen.setTabText(self.tabGen.indexOf(self.tabGenPer), _translate("Interface", "Periódica", None))
        self.txtGenTrapRiseTime.setText(_translate("Interface", "25", None))
        self.lblGenTrapBaseV.setText(_translate("Interface", "Base (V)", None))
        self.lblGenTrapClimbTime.setText(_translate("Interface", "T Subida (%)", None))
        self.txtGenTrapTopV.setText(_translate("Interface", "10", None))
        self.txtGenTrapPlateauTime.setText(_translate("Interface", "50", None))
        self.lblGenTrapTopV.setText(_translate("Interface", "Topo (V)", None))
        self.txtGenTrapBaseV.setText(_translate("Interface", "0", None))
        self.lblGenTrapTopTime.setText(_translate("Interface", "T Topo (%)", None))
        self.lblGenTrapDescendTime.setText(_translate("Interface", "T Descida (%)", None))
        self.txtGenTrapFallTime.setText(_translate("Interface", "25", None))
        self.tabGen.setTabText(self.tabGen.indexOf(self.tabGenTrap), _translate("Interface", "Trapezoidal", None))
        self.txtGenLinEndV.setText(_translate("Interface", "10", None))
        self.txtGenLinStartV.setText(_translate("Interface", "0", None))
        self.lblGenLinStartV.setText(_translate("Interface", "Início (V)", None))
        self.lblGenLinEndV.setText(_translate("Interface", "Fim (V)", None))
        self.tabGen.setTabText(self.tabGen.indexOf(self.tabGenLin), _translate("Interface", "Linear", None))
        self.lblGenFile.setText(_translate("Interface", "Arquivo", None))
        self.btGenFileSelect.setText(_translate("Interface", "Escolher...", None))
        self.tabGen.setTabText(self.tabGen.indexOf(self.tabGenFile), _translate("Interface", "Arquivo", None))
        self.btSyncGenSend.setText(_translate("Interface", "Enviar", None))
        self.btConnect.setText(_translate("Interface", "Conectar", None))
        self.lblSerialAddress.setText(_translate("Interface", "PUC:", None))
        self.lblSerialPort.setText(_translate("Interface", "Porta:", None))
        self.txtSerialPort.setText(_translate("Interface", "COM4", None))
        self.txtSerialPort.setPlaceholderText(_translate("Interface", "PORTA", None))
        self.btReset.setText(_translate("Interface", "RESET", None))
        self.cbSyncPtSize.setItemText(0, _translate("Interface", "16-bits", None))
        self.cbSyncPtSize.setItemText(1, _translate("Interface", "18-bits", None))
        self.lblSyncClk.setText(_translate("Interface", "Fonte Clock", None))
        self.lblSyncClkPulseBit.setText(_translate("Interface", "Bit Pulso", None))
        self.lblSyncConfig.setText(_translate("Interface", "Configuração Síncrono", None))
        self.lblSyncClkOutBit.setText(_translate("Interface", "Bit Output", None))
        self.lblSyncClkFreq.setText(_translate("Interface", "Frequência (Hz)", None))
        self.cbSyncClkPulseBit.setItemText(0, _translate("Interface", "Nenhum", None))
        self.cbSyncClkPulseBit.setItemText(1, _translate("Interface", "0", None))
        self.cbSyncClkPulseBit.setItemText(2, _translate("Interface", "1", None))
        self.cbSyncClkPulseBit.setItemText(3, _translate("Interface", "2", None))
        self.cbSyncClkPulseBit.setItemText(4, _translate("Interface", "3", None))
        self.cbSyncClkPulseBit.setItemText(5, _translate("Interface", "4", None))
        self.cbSyncClkPulseBit.setItemText(6, _translate("Interface", "5", None))
        self.cbSyncClkPulseBit.setItemText(7, _translate("Interface", "6", None))
        self.cbSyncClkPulseBit.setItemText(8, _translate("Interface", "7", None))
        self.lblSyncClkDiv.setText(_translate("Interface", "Divisor", None))
        self.cbSyncClkSrc.setItemText(0, _translate("Interface", "Timer", None))
        self.cbSyncClkSrc.setItemText(1, _translate("Interface", "Externo", None))
        self.cbSyncClkSrc.setItemText(2, _translate("Interface", "Serial", None))
        self.cbSyncClkOutBit.setItemText(0, _translate("Interface", "Nenhum", None))
        self.cbSyncClkOutBit.setItemText(1, _translate("Interface", "0", None))
        self.cbSyncClkOutBit.setItemText(2, _translate("Interface", "1", None))
        self.cbSyncClkOutBit.setItemText(3, _translate("Interface", "2", None))
        self.cbSyncClkOutBit.setItemText(4, _translate("Interface", "3", None))
        self.cbSyncClkOutBit.setItemText(5, _translate("Interface", "4", None))
        self.cbSyncClkOutBit.setItemText(6, _translate("Interface", "5", None))
        self.cbSyncClkOutBit.setItemText(7, _translate("Interface", "6", None))
        self.cbSyncClkOutBit.setItemText(8, _translate("Interface", "7", None))
        self.chkSyncInEn.setText(_translate("Interface", "Entrada", None))
        self.lblSyncInPtSize.setText(_translate("Interface", "Precisão", None))
        self.lblSyncInNPts.setText(_translate("Interface", "Nº Pontos", None))
        self.chkSyncOutEn.setToolTip(_translate("Interface", "A cada passo, ler um ponto da memória FLASH e escrever na saída analógica", None))
        self.chkSyncOutEn.setText(_translate("Interface", "Saída", None))
        self.lblDOLess.setText(_translate("Interface", "-", None))
        self.lblDOMost.setText(_translate("Interface", "+", None))
        self.lblDO.setText(_translate("Interface", "Saída Digital", None))
        self.btDORead.setToolTip(_translate("Interface", "Atualizar com último valor escrito na saída digital", None))
        self.btDORead.setText(_translate("Interface", "⟲", None))
        self.lblDILeast.setText(_translate("Interface", "-", None))
        self.lblDIMost.setText(_translate("Interface", "+", None))
        self.btDIRead.setText(_translate("Interface", "⟲", None))
        self.lblDI.setText(_translate("Interface", "Entrada Digital", None))
        self.lblReadCaptureFile.setText(_translate("Interface", "Arquivo", None))
        self.btReadCaptureFileChoose.setText(_translate("Interface", "Escolher...", None))
        self.btReadCapture.setText(_translate("Interface", "Ler", None))
        self.lblReadCapture.setText(_translate("Interface", "Ler Captura", None))

