#ifndef PUC_ANALOG_H
#define PUC_ANALOG_H

#define ANALOG_BOARD_TYPE   BOARD_ANALOG
#define ANALOG_VAR_TYPES    VAR_ANALOG_INPUT, VAR_ANALOG_OUTPUT
#define ANALOG_CURVE_TYPES
#define ANALOG_FUNC_TYPES
#define ANALOG_INIT         analog_init

#endif
