# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface_Agilent_34401A.ui'
#
# Created: Mon Feb 11 17:49:19 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(860, 511)
        MainWindow.setMinimumSize(QtCore.QSize(860, 511))
        MainWindow.setMaximumSize(QtCore.QSize(860, 511))
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gb_Geral = QtGui.QGroupBox(self.centralwidget)
        self.gb_Geral.setEnabled(False)
        self.gb_Geral.setGeometry(QtCore.QRect(0, 0, 861, 402))
        self.gb_Geral.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.gb_Geral.setFont(font)
        self.gb_Geral.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.gb_Geral.setObjectName(_fromUtf8("gb_Geral"))
        self.widget = matplotlibWidget(self.gb_Geral)
        self.widget.setGeometry(QtCore.QRect(342, 143, 517, 227))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.cb_TIntegracao = QtGui.QComboBox(self.gb_Geral)
        self.cb_TIntegracao.setGeometry(QtCore.QRect(229, 53, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_TIntegracao.setFont(font)
        self.cb_TIntegracao.setObjectName(_fromUtf8("cb_TIntegracao"))
        self.cb_TIntegracao.addItem(_fromUtf8(""))
        self.cb_TIntegracao.addItem(_fromUtf8(""))
        self.cb_TIntegracao.addItem(_fromUtf8(""))
        self.cb_TIntegracao.addItem(_fromUtf8(""))
        self.cb_TIntegracao.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(self.gb_Geral)
        self.label_5.setGeometry(QtCore.QRect(29, 53, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lcd_leitura = QtGui.QLCDNumber(self.gb_Geral)
        self.lcd_leitura.setGeometry(QtCore.QRect(20, 170, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcd_leitura.setFont(font)
        self.lcd_leitura.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.lcd_leitura.setNumDigits(10)
        self.lcd_leitura.setProperty("value", 0.0)
        self.lcd_leitura.setObjectName(_fromUtf8("lcd_leitura"))
        self.line = QtGui.QFrame(self.gb_Geral)
        self.line.setGeometry(QtCore.QRect(0, 250, 340, 3))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.gb_Geral)
        self.line_2.setGeometry(QtCore.QRect(340, 11, 3, 390))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.cb_Salvar = QtGui.QCheckBox(self.gb_Geral)
        self.cb_Salvar.setGeometry(QtCore.QRect(448, 74, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cb_Salvar.setFont(font)
        self.cb_Salvar.setObjectName(_fromUtf8("cb_Salvar"))
        self.line_4 = QtGui.QFrame(self.gb_Geral)
        self.line_4.setGeometry(QtCore.QRect(341, 139, 517, 10))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_8 = QtGui.QLabel(self.gb_Geral)
        self.label_8.setGeometry(QtCore.QRect(764, 33, 91, 91))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setPixmap(QtGui.QPixmap(_fromUtf8("Imagens/LNLS_logo.png")))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.pb_Iniciar = QtGui.QPushButton(self.gb_Geral)
        self.pb_Iniciar.setGeometry(QtCore.QRect(350, 27, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_Iniciar.setFont(font)
        self.pb_Iniciar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pb_Iniciar.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Imagens/1351621501_Check.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_Iniciar.setIcon(icon)
        self.pb_Iniciar.setIconSize(QtCore.QSize(30, 30))
        self.pb_Iniciar.setObjectName(_fromUtf8("pb_Iniciar"))
        self.pb_Parar = QtGui.QPushButton(self.gb_Geral)
        self.pb_Parar.setEnabled(False)
        self.pb_Parar.setGeometry(QtCore.QRect(560, 27, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_Parar.setFont(font)
        self.pb_Parar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pb_Parar.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Imagens/1351621507_Delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_Parar.setIcon(icon1)
        self.pb_Parar.setIconSize(QtCore.QSize(30, 30))
        self.pb_Parar.setObjectName(_fromUtf8("pb_Parar"))
        self.gb_btmanuais = QtGui.QGroupBox(self.gb_Geral)
        self.gb_btmanuais.setGeometry(QtCore.QRect(24, 100, 281, 51))
        self.gb_btmanuais.setTitle(_fromUtf8(""))
        self.gb_btmanuais.setObjectName(_fromUtf8("gb_btmanuais"))
        self.tb_Medir = QtGui.QToolButton(self.gb_btmanuais)
        self.tb_Medir.setGeometry(QtCore.QRect(224, 10, 30, 30))
        self.tb_Medir.setStyleSheet(_fromUtf8("background-color: rgb(0, 170, 0);"))
        self.tb_Medir.setText(_fromUtf8(""))
        self.tb_Medir.setObjectName(_fromUtf8("tb_Medir"))
        self.tb_Reiniciar = QtGui.QToolButton(self.gb_btmanuais)
        self.tb_Reiniciar.setGeometry(QtCore.QRect(74, 10, 30, 30))
        self.tb_Reiniciar.setStyleSheet(_fromUtf8("background-color: rgb(255, 85, 0);"))
        self.tb_Reiniciar.setText(_fromUtf8(""))
        self.tb_Reiniciar.setObjectName(_fromUtf8("tb_Reiniciar"))
        self.tb_Acessar = QtGui.QToolButton(self.gb_btmanuais)
        self.tb_Acessar.setGeometry(QtCore.QRect(24, 10, 30, 30))
        self.tb_Acessar.setMinimumSize(QtCore.QSize(0, 0))
        self.tb_Acessar.setStyleSheet(_fromUtf8("background-color: rgb(170, 0, 127);"))
        self.tb_Acessar.setText(_fromUtf8(""))
        self.tb_Acessar.setObjectName(_fromUtf8("tb_Acessar"))
        self.tb_Limpar = QtGui.QToolButton(self.gb_btmanuais)
        self.tb_Limpar.setGeometry(QtCore.QRect(124, 10, 30, 30))
        self.tb_Limpar.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        self.tb_Limpar.setText(_fromUtf8(""))
        self.tb_Limpar.setObjectName(_fromUtf8("tb_Limpar"))
        self.tb_Configurar = QtGui.QToolButton(self.gb_btmanuais)
        self.tb_Configurar.setGeometry(QtCore.QRect(174, 10, 30, 30))
        self.tb_Configurar.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.tb_Configurar.setText(_fromUtf8(""))
        self.tb_Configurar.setObjectName(_fromUtf8("tb_Configurar"))
        self.lcd_status = QtGui.QLCDNumber(self.gb_Geral)
        self.lcd_status.setGeometry(QtCore.QRect(454, 106, 60, 30))
        self.lcd_status.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);"))
        self.lcd_status.setSmallDecimalPoint(False)
        self.lcd_status.setNumDigits(3)
        self.lcd_status.setDigitCount(3)
        self.lcd_status.setProperty("value", 100.0)
        self.lcd_status.setObjectName(_fromUtf8("lcd_status"))
        self.label_10 = QtGui.QLabel(self.gb_Geral)
        self.label_10.setGeometry(QtCore.QRect(360, 113, 90, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.gb_Geral)
        self.label_11.setGeometry(QtCore.QRect(530, 113, 160, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.line_3 = QtGui.QFrame(self.gb_Geral)
        self.line_3.setGeometry(QtCore.QRect(760, 12, 3, 131))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_5 = QtGui.QFrame(self.gb_Geral)
        self.line_5.setGeometry(QtCore.QRect(341, 100, 420, 3))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.cb_pontosgrafico = QtGui.QComboBox(self.gb_Geral)
        self.cb_pontosgrafico.setGeometry(QtCore.QRect(693, 110, 60, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_pontosgrafico.setFont(font)
        self.cb_pontosgrafico.setObjectName(_fromUtf8("cb_pontosgrafico"))
        self.cb_pontosgrafico.addItem(_fromUtf8(""))
        self.cb_pontosgrafico.addItem(_fromUtf8(""))
        self.cb_pontosgrafico.addItem(_fromUtf8(""))
        self.cb_pontosgrafico.addItem(_fromUtf8(""))
        self.gb_medidas = QtGui.QGroupBox(self.gb_Geral)
        self.gb_medidas.setGeometry(QtCore.QRect(0, 251, 340, 150))
        self.gb_medidas.setTitle(_fromUtf8(""))
        self.gb_medidas.setObjectName(_fromUtf8("gb_medidas"))
        self.layoutWidget = QtGui.QWidget(self.gb_medidas)
        self.layoutWidget.setGeometry(QtCore.QRect(15, 110, 307, 26))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rb_TensaoV = QtGui.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rb_TensaoV.setFont(font)
        self.rb_TensaoV.setObjectName(_fromUtf8("rb_TensaoV"))
        self.horizontalLayout.addWidget(self.rb_TensaoV)
        self.rb_CampoT = QtGui.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rb_CampoT.setFont(font)
        self.rb_CampoT.setObjectName(_fromUtf8("rb_CampoT"))
        self.horizontalLayout.addWidget(self.rb_CampoT)
        self.rb_CampoG = QtGui.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rb_CampoG.setFont(font)
        self.rb_CampoG.setObjectName(_fromUtf8("rb_CampoG"))
        self.horizontalLayout.addWidget(self.rb_CampoG)
        self.layoutWidget1 = QtGui.QWidget(self.gb_medidas)
        self.layoutWidget1.setGeometry(QtCore.QRect(15, 10, 307, 91))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.le_nmedidas = QtGui.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_nmedidas.setFont(font)
        self.le_nmedidas.setObjectName(_fromUtf8("le_nmedidas"))
        self.gridLayout.addWidget(self.le_nmedidas, 0, 1, 1, 2)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 2)
        self.le_intervalo = QtGui.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_intervalo.setFont(font)
        self.le_intervalo.setObjectName(_fromUtf8("le_intervalo"))
        self.gridLayout.addWidget(self.le_intervalo, 1, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 2)
        self.le_conversao = QtGui.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_conversao.setFont(font)
        self.le_conversao.setObjectName(_fromUtf8("le_conversao"))
        self.gridLayout.addWidget(self.le_conversao, 2, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.gb_Geral)
        self.label_12.setGeometry(QtCore.QRect(391, 370, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.le_media = QtGui.QLineEdit(self.gb_Geral)
        self.le_media.setGeometry(QtCore.QRect(450, 371, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_media.setFont(font)
        self.le_media.setText(_fromUtf8(""))
        self.le_media.setReadOnly(True)
        self.le_media.setObjectName(_fromUtf8("le_media"))
        self.le_desvio = QtGui.QLineEdit(self.gb_Geral)
        self.le_desvio.setGeometry(QtCore.QRect(669, 372, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_desvio.setFont(font)
        self.le_desvio.setText(_fromUtf8(""))
        self.le_desvio.setReadOnly(True)
        self.le_desvio.setObjectName(_fromUtf8("le_desvio"))
        self.label_13 = QtGui.QLabel(self.gb_Geral)
        self.label_13.setGeometry(QtCore.QRect(610, 371, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 401, 861, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.cb_PortaCom = QtGui.QComboBox(self.groupBox)
        self.cb_PortaCom.setGeometry(QtCore.QRect(220, 30, 90, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_PortaCom.setFont(font)
        self.cb_PortaCom.setObjectName(_fromUtf8("cb_PortaCom"))
        self.cb_PortaCom.addItem(_fromUtf8(""))
        self.cb_PortaCom.addItem(_fromUtf8(""))
        self.cb_PortaCom.addItem(_fromUtf8(""))
        self.cb_PortaCom.addItem(_fromUtf8(""))
        self.cb_PortaCom.addItem(_fromUtf8(""))
        self.cb_PortaCom.addItem(_fromUtf8(""))
        self.cb_PortaCom.addItem(_fromUtf8(""))
        self.cb_PortaCom.addItem(_fromUtf8(""))
        self.cb_PortaCom.addItem(_fromUtf8(""))
        self.cb_PortaCom.addItem(_fromUtf8(""))
        self.cb_PortaCom.addItem(_fromUtf8(""))
        self.cb_PortaCom.addItem(_fromUtf8(""))
        self.cb_PortaCom.addItem(_fromUtf8(""))
        self.cb_PortaCom.addItem(_fromUtf8(""))
        self.cb_PortaCom.addItem(_fromUtf8(""))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 59, 281, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(330, 31, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.le_TempoEspera = QtGui.QLineEdit(self.groupBox)
        self.le_TempoEspera.setGeometry(QtCore.QRect(530, 30, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_TempoEspera.setFont(font)
        self.le_TempoEspera.setObjectName(_fromUtf8("le_TempoEspera"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(360, 60, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pb_Conectar = QtGui.QPushButton(self.groupBox)
        self.pb_Conectar.setGeometry(QtCore.QRect(604, 26, 250, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_Conectar.setFont(font)
        self.pb_Conectar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pb_Conectar.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Imagens/connect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_Conectar.setIcon(icon2)
        self.pb_Conectar.setIconSize(QtCore.QSize(30, 30))
        self.pb_Conectar.setObjectName(_fromUtf8("pb_Conectar"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 860, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pb_Conectar, self.pb_Iniciar)
        MainWindow.setTabOrder(self.pb_Iniciar, self.pb_Parar)
        MainWindow.setTabOrder(self.pb_Parar, self.cb_PortaCom)
        MainWindow.setTabOrder(self.cb_PortaCom, self.le_TempoEspera)
        MainWindow.setTabOrder(self.le_TempoEspera, self.cb_TIntegracao)
        MainWindow.setTabOrder(self.cb_TIntegracao, self.tb_Acessar)
        MainWindow.setTabOrder(self.tb_Acessar, self.tb_Reiniciar)
        MainWindow.setTabOrder(self.tb_Reiniciar, self.tb_Limpar)
        MainWindow.setTabOrder(self.tb_Limpar, self.tb_Configurar)
        MainWindow.setTabOrder(self.tb_Configurar, self.tb_Medir)
        MainWindow.setTabOrder(self.tb_Medir, self.le_nmedidas)
        MainWindow.setTabOrder(self.le_nmedidas, self.le_intervalo)
        MainWindow.setTabOrder(self.le_intervalo, self.cb_Salvar)
        MainWindow.setTabOrder(self.cb_Salvar, self.le_conversao)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Agilent 34401A - Serial - Tensão/Campo", None))
        self.gb_Geral.setTitle(_translate("MainWindow", "Configurações e Medição", None))
        self.cb_TIntegracao.setToolTip(_translate("MainWindow", "Ciclo de Redes", None))
        self.cb_TIntegracao.setItemText(0, _translate("MainWindow", "0.02", None))
        self.cb_TIntegracao.setItemText(1, _translate("MainWindow", "0.2", None))
        self.cb_TIntegracao.setItemText(2, _translate("MainWindow", "1", None))
        self.cb_TIntegracao.setItemText(3, _translate("MainWindow", "10", None))
        self.cb_TIntegracao.setItemText(4, _translate("MainWindow", "100", None))
        self.label_5.setText(_translate("MainWindow", "Tempo de Integração :", None))
        self.cb_Salvar.setStatusTip(_translate("MainWindow", "Salvar resultados em arquivo quando selecionado", None))
        self.cb_Salvar.setText(_translate("MainWindow", "Salvar Medidas em Arquivo", None))
        self.pb_Iniciar.setStatusTip(_translate("MainWindow", "Iniciar leitura de dados", None))
        self.pb_Iniciar.setText(_translate("MainWindow", "Iniciar Medições", None))
        self.pb_Parar.setStatusTip(_translate("MainWindow", "Parar imediatamente a leitura de dados", None))
        self.pb_Parar.setText(_translate("MainWindow", "Parar Medições", None))
        self.tb_Medir.setToolTip(_translate("MainWindow", "Medir", None))
        self.tb_Medir.setStatusTip(_translate("MainWindow", "Realizar Coleta de Dados", None))
        self.tb_Reiniciar.setToolTip(_translate("MainWindow", "Reiniciar", None))
        self.tb_Reiniciar.setStatusTip(_translate("MainWindow", "Reiniciar para configurações de fábrica", None))
        self.tb_Acessar.setToolTip(_translate("MainWindow", "Acessar", None))
        self.tb_Acessar.setStatusTip(_translate("MainWindow", "Configurar para acesso remoto", None))
        self.tb_Limpar.setToolTip(_translate("MainWindow", "Limpar", None))
        self.tb_Limpar.setStatusTip(_translate("MainWindow", "Limpar erros", None))
        self.tb_Configurar.setToolTip(_translate("MainWindow", "Configurar", None))
        self.tb_Configurar.setStatusTip(_translate("MainWindow", "Configurar leitura de tensão e tempo de integração selecionado", None))
        self.label_10.setText(_translate("MainWindow", "Coletas (%) :", None))
        self.label_11.setText(_translate("MainWindow", "Máximo Pontos Gráfico :", None))
        self.cb_pontosgrafico.setToolTip(_translate("MainWindow", "Ciclo de Redes", None))
        self.cb_pontosgrafico.setItemText(0, _translate("MainWindow", "10", None))
        self.cb_pontosgrafico.setItemText(1, _translate("MainWindow", "100", None))
        self.cb_pontosgrafico.setItemText(2, _translate("MainWindow", "500", None))
        self.cb_pontosgrafico.setItemText(3, _translate("MainWindow", "1000", None))
        self.rb_TensaoV.setText(_translate("MainWindow", "Tensão [V]", None))
        self.rb_CampoT.setText(_translate("MainWindow", "Campo [T]", None))
        self.rb_CampoG.setText(_translate("MainWindow", "Campo [G]", None))
        self.label_6.setText(_translate("MainWindow", "Número de Medidas :", None))
        self.le_nmedidas.setText(_translate("MainWindow", "100", None))
        self.label_7.setText(_translate("MainWindow", "Intervalo entre Medidas (s) :", None))
        self.le_intervalo.setText(_translate("MainWindow", "1", None))
        self.label_9.setText(_translate("MainWindow", "Tensão -> Campo (V/T) :", None))
        self.le_conversao.setStatusTip(_translate("MainWindow", "Fator de conversar de tensão para campo. Volts por Teslas", None))
        self.le_conversao.setText(_translate("MainWindow", "5", None))
        self.label_12.setText(_translate("MainWindow", "Média :", None))
        self.label_13.setText(_translate("MainWindow", "Desvio :", None))
        self.groupBox.setTitle(_translate("MainWindow", "Conexão", None))
        self.cb_PortaCom.setItemText(0, _translate("MainWindow", "COM1", None))
        self.cb_PortaCom.setItemText(1, _translate("MainWindow", "COM2", None))
        self.cb_PortaCom.setItemText(2, _translate("MainWindow", "COM3", None))
        self.cb_PortaCom.setItemText(3, _translate("MainWindow", "COM4", None))
        self.cb_PortaCom.setItemText(4, _translate("MainWindow", "COM5", None))
        self.cb_PortaCom.setItemText(5, _translate("MainWindow", "COM6", None))
        self.cb_PortaCom.setItemText(6, _translate("MainWindow", "COM7", None))
        self.cb_PortaCom.setItemText(7, _translate("MainWindow", "COM8", None))
        self.cb_PortaCom.setItemText(8, _translate("MainWindow", "COM9", None))
        self.cb_PortaCom.setItemText(9, _translate("MainWindow", "COM10", None))
        self.cb_PortaCom.setItemText(10, _translate("MainWindow", "COM11", None))
        self.cb_PortaCom.setItemText(11, _translate("MainWindow", "COM12", None))
        self.cb_PortaCom.setItemText(12, _translate("MainWindow", "COM13", None))
        self.cb_PortaCom.setItemText(13, _translate("MainWindow", "COM14", None))
        self.cb_PortaCom.setItemText(14, _translate("MainWindow", "COM15", None))
        self.label.setText(_translate("MainWindow", "Porta de Comunicação :", None))
        self.label_2.setText(_translate("MainWindow", "Baudrate 9600, Databits 8, StopBits 1, No Parity", None))
        self.label_3.setText(_translate("MainWindow", "Tempo de Espera (ms) :", None))
        self.le_TempoEspera.setText(_translate("MainWindow", "100", None))
        self.label_4.setText(_translate("MainWindow", "Ajuste de timeout da porta serial", None))
        self.pb_Conectar.setStatusTip(_translate("MainWindow", "Conecta dispositivo usando a porta serial", None))
        self.pb_Conectar.setText(_translate("MainWindow", "Conectar Dispositivo", None))

from PlotGUI import matplotlibWidget
